#!/bin/sh

JQL_DIR=/root/jubaql-server
ARCH=target/scala-2.10
MY_IP=$(ip route get 8.8.8.8 | grep -Po 'src \K.+')

export HADOOP_CONF_DIR=$JQL_DIR/processor/src/main/resources

exec java -Dspark.distribution="$SPARK_DIST" \
  -Djubaql.checkpointdir=hdfs:///tmp/spark \
  -Drun.mode=production:1:3 \
  -Djubaql.zookeeper=zk:2181 \
  -Djubaql.processor.fatjar=$JQL_DIR/processor/$ARCH/jubaql-processor-assembly-1.3.0.jar \
  -jar $JQL_DIR/gateway/$ARCH/jubaql-gateway-assembly-1.3.0.jar \
  -i $MY_IP
